import os
import logging
import requests
from datetime import datetime
from sqlalchemy.orm import Session
from fpdf import FPDF
import matplotlib.pyplot as plt
import matplotlib

# Ustawienie backendu "Agg"
matplotlib.use('Agg')

from app.database import Lead, Client, Campaign

logger = logging.getLogger("reporter")

# --- KONFIGURACJA KOLORYSTYCZNA ---
COLOR_PRIMARY = (28, 57, 105)      # Navy Blue
COLOR_SECONDARY = (240, 240, 240)  # Light Grey
COLOR_ACCENT = (231, 76, 60)       # Red
COLOR_TEXT = (50, 50, 50)          # Dark Grey

# --- MENEDŻER CZCIONEK (Robust Version) ---
def ensure_fonts():
    """Pobiera czcionkę Unicode ze stabilnego źródła."""
    files_dir = os.path.join(os.getcwd(), "files")
    os.makedirs(files_dir, exist_ok=True)
    
    font_path = os.path.join(files_dir, "DejaVuSans.ttf")
    # Zmiana URL na raw.githubusercontent (bezpośredni binarny)
    font_url = "https://raw.githubusercontent.com/dejavu-fonts/dejavu-fonts/master/ttf/DejaVuSans.ttf"
    
    if not os.path.exists(font_path):
        print("⏳ [REPORTER] Pobieranie czcionki Unicode (DejaVuSans)...")
        try:
            r = requests.get(font_url)
            with open(font_path, 'wb') as f:
                f.write(r.content)
            
            # Weryfikacja czy pobrano plik (a nie stronę błędu)
            if os.path.getsize(font_path) < 10000: # Mniej niż 10KB to na pewno błąd
                print("❌ Pobrany plik jest uszkodzony. Usuwam.")
                os.remove(font_path)
                return None
                
            print("✅ Czcionka pobrana poprawnie.")
        except Exception as e:
            print(f"❌ Błąd pobierania czcionki: {e}")
            return None
    
    return font_path

class EnterpriseReport(FPDF):
    """Klasa PDF w stylu Corporate."""
    
    def __init__(self):
        super().__init__()
        self.unicode_available = False
        
        # Próba rejestracji Unicode
        font_path = ensure_fonts()
        if font_path and os.path.exists(font_path):
            try:
                self.add_font("DejaVu", "", font_path)
                self.add_font("DejaVu", "B", font_path)
                self.add_font("DejaVu", "I", font_path)
                self.unicode_available = True
            except Exception as e:
                print(f"⚠️ Nie udało się załadować czcionki: {e}. Używam standardowej.")
    
    def safe_text(self, text):
        """Zabezpiecza tekst przed błędem Unicode jeśli brak czcionki."""
        if self.unicode_available:
            return text
        # Fallback: usuń polskie znaki
        replacements = {
            'ą': 'a', 'ć': 'c', 'ę': 'e', 'ł': 'l', 'ń': 'n', 'ó': 'o', 'ś': 's', 'ź': 'z', 'ż': 'z',
            'Ą': 'A', 'Ć': 'C', 'Ę': 'E', 'Ł': 'L', 'Ń': 'N', 'Ó': 'O', 'Ś': 'S', 'Ź': 'Z', 'Ż': 'Z'
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        return text.encode('latin-1', 'replace').decode('latin-1')

    def header(self):
        # 1. LOGO
        logo_path = os.path.join(os.getcwd(), "files", "logo.png")
        if os.path.exists(logo_path):
            try:
                self.image(logo_path, 10, 8, 33)
            except: pass
        else:
            font = 'DejaVu' if self.unicode_available else 'Helvetica'
            self.set_font(font, 'B', 20)
            self.set_text_color(*COLOR_PRIMARY)
            self.cell(40, 10, 'NEXUS', 0, 0, 'L')

        # 2. TYTUŁ
        font = 'DejaVu' if self.unicode_available else 'Helvetica'
        self.set_font(font, 'B', 12)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, 'RAPORT TYGODNIOWY', 0, 1, 'R')
        
        # 3. LINIA
        self.set_draw_color(*COLOR_PRIMARY)
        self.set_line_width(0.5)
        self.line(10, 25, 200, 25)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        font = 'DejaVu' if self.unicode_available else 'Helvetica'
        self.set_font(font, 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'CONFIDENTIAL - Generated by AI Agent | Strona {self.page_no()}', 0, 0, 'C')

def get_client_stats(session: Session, client_id: int):
    """Agreguje dane statystyczne."""
    total_leads = session.query(Lead).join(Campaign).filter(Campaign.client_id == client_id).count()
    
    sent = session.query(Lead).join(Campaign).filter(
        Campaign.client_id == client_id,
        Lead.status.in_(['SENT', 'REPLIED', 'HOT_LEAD', 'NOT_INTERESTED', 'BOUNCED'])
    ).count()
    
    replied = session.query(Lead).join(Campaign).filter(
        Campaign.client_id == client_id,
        Lead.status.in_(['REPLIED', 'HOT_LEAD', 'NOT_INTERESTED'])
    ).count()
    
    hot_leads = session.query(Lead).join(Campaign).filter(
        Campaign.client_id == client_id,
        Lead.status == 'HOT_LEAD'
    ).count()

    bounced = session.query(Lead).join(Campaign).filter(
        Campaign.client_id == client_id,
        Lead.status == 'BOUNCED'
    ).count()

    reply_rate = (replied / sent * 100) if sent > 0 else 0.0
    interest_rate = (hot_leads / replied * 100) if replied > 0 else 0.0
    bounce_rate = (bounced / sent * 100) if sent > 0 else 0.0

    return {
        "sourced": total_leads,
        "contacted": sent,
        "replies": replied,
        "hot_leads": hot_leads,
        "bounces": bounced,
        "metrics": {
            "reply_rate": round(reply_rate, 2),
            "interest_rate": round(interest_rate, 2),
            "bounce_rate": round(bounce_rate, 2)
        }
    }

def generate_modern_chart(stats, client_name):
    """Wykres Doughnut."""
    labels = ['Brak odp.', 'Rozmowy', 'Bounces']
    sizes = [
        max(0, stats['contacted'] - stats['replies'] - stats['bounces']),
        stats['replies'],
        stats['bounces']
    ]
    colors = ['#bdc3c7', '#27ae60', '#c0392b']

    clean_labels, clean_sizes, clean_colors = [], [], []
    for l, s, c in zip(labels, sizes, colors):
        if s > 0:
            clean_labels.append(l)
            clean_sizes.append(s)
            clean_colors.append(c)

    if not clean_sizes: return None

    fig, ax = plt.subplots(figsize=(7, 4))
    wedges, texts, autotexts = ax.pie(
        clean_sizes, labels=clean_labels, autopct='%1.1f%%', 
        startangle=90, colors=clean_colors, pctdistance=0.85,
        textprops=dict(color="black")
    )
    
    centre_circle = plt.Circle((0,0),0.70,fc='white')
    fig.gca().add_artist(centre_circle)
    
    plt.setp(autotexts, size=9, weight="bold", color="white")
    plt.title(f"Skutecznosc Kampanii", fontsize=14, pad=20)
    plt.tight_layout()
    
    filename = f"chart_{client_name}.png"
    plt.savefig(filename, dpi=100)
    plt.close()
    return filename

def create_pdf_report(session: Session, client_id: int):
    """Generator PDF."""
    client = session.query(Client).filter(Client.id == client_id).first()
    if not client:
        print("❌ Nie znaleziono klienta.")
        return None

    stats = get_client_stats(session, client_id)
    today_str = datetime.now().strftime('%Y-%m-%d')
    pdf_filename = f"Raport_{client.name}_{today_str}.pdf"

    pdf = EnterpriseReport()
    pdf.add_page()
    
    # Wybór czcionki w zależności od dostępności
    font_main = "DejaVu" if pdf.unicode_available else "Helvetica"
    
    # --- TYTUŁ ---
    pdf.set_font(font_main, "B", 16)
    pdf.set_text_color(*COLOR_PRIMARY)
    pdf.cell(0, 10, pdf.safe_text(f"Podsumowanie Efektywności: {client.name}"), new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font(font_main, "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, pdf.safe_text(f"Okres raportowania: Do dnia {today_str}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # --- KPI CARDS ---
    def draw_kpi_card(x, title, value, subtext, color_bg=None):
        pdf.set_xy(x, pdf.get_y())
        pdf.set_fill_color(*(color_bg if color_bg else (245, 245, 245)))
        pdf.rect(x, pdf.get_y(), 55, 30, 'F')
        
        pdf.set_xy(x, pdf.get_y() + 3)
        pdf.set_font(font_main, "", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(55, 5, pdf.safe_text(title), 0, 2, 'C')
        
        pdf.set_font(font_main, "B", 16)
        pdf.set_text_color(*COLOR_PRIMARY)
        pdf.cell(55, 10, str(value), 0, 2, 'C')
        
        pdf.set_font(font_main, "I", 7)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(55, 5, pdf.safe_text(subtext), 0, 2, 'C')
        pdf.set_y(pdf.get_y() - 23)

    y_start = pdf.get_y()
    draw_kpi_card(10, "KONTAKTY (Wysłane)", stats['contacted'], f"Z bazy {stats['sourced']} firm")
    draw_kpi_card(75, "ODPOWIEDZI", stats['replies'], f"Reply Rate: {stats['metrics']['reply_rate']}%")
    pdf.set_fill_color(230, 250, 230)
    draw_kpi_card(140, "HOT LEADS", stats['hot_leads'], f"Conversion: {stats['metrics']['interest_rate']}%", color_bg=(230, 250, 230))
    
    pdf.ln(35)

    # --- ANALIZA ---
    pdf.set_font(font_main, "B", 12)
    pdf.set_text_color(*COLOR_TEXT)
    pdf.cell(0, 10, pdf.safe_text("Analiza Lejka Sprzedaży"), 0, 1)
    
    chart_file = generate_modern_chart(stats, client.name)
    if chart_file:
        pdf.image(chart_file, x=15, w=180)
        os.remove(chart_file)
        pdf.ln(5)

    # --- TABELA ---
    pdf.ln(10)
    pdf.set_font(font_main, "B", 12)
    pdf.cell(0, 10, pdf.safe_text("Wskaźniki Operacyjne"), 0, 1)

    pdf.set_fill_color(*COLOR_PRIMARY)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(font_main, "B", 9)
    
    col_w = 45
    h = 8
    
    pdf.cell(col_w, h, "Metryka", 1, 0, 'C', True)
    pdf.cell(col_w, h, "Wynik", 1, 0, 'C', True)
    pdf.cell(col_w, h, "Status", 1, 0, 'C', True)
    pdf.cell(col_w, h, "Uwagi", 1, 1, 'C', True)

    pdf.set_text_color(*COLOR_TEXT)
    pdf.set_font(font_main, "", 9)
    
    def add_row(metric, value, status, note, fill=False):
        pdf.set_fill_color(245, 245, 245)
        pdf.cell(col_w, h, pdf.safe_text(metric), 1, 0, 'L', fill)
        pdf.cell(col_w, h, str(value), 1, 0, 'C', fill)
        pdf.cell(col_w, h, pdf.safe_text(status), 1, 0, 'C', fill)
        pdf.cell(col_w, h, pdf.safe_text(note), 1, 1, 'C', fill)

    add_row("Dostarczalność", f"{100 - stats['metrics']['bounce_rate']}%", "OK" if stats['metrics']['bounce_rate'] < 5 else "UWAGA", "Zdrowie domeny")
    add_row("Zaangażowanie", f"{stats['metrics']['reply_rate']}%", "NORMA" if stats['metrics']['reply_rate'] > 1 else "NISKIE", "Odpowiedzi")
    add_row("Konwersja (Hot)", f"{stats['metrics']['interest_rate']}%", "WYSOKA" if stats['metrics']['interest_rate'] > 10 else "ŚREDNIA", "Jakość Leadów")

    # --- PODSUMOWANIE ---
    pdf.ln(15)
    pdf.set_fill_color(240, 248, 255)
    pdf.rect(10, pdf.get_y(), 190, 30, 'F')
    
    pdf.set_xy(15, pdf.get_y() + 3)
    pdf.set_font(font_main, "B", 10)
    pdf.set_text_color(*COLOR_PRIMARY)
    pdf.cell(0, 5, "PODSUMOWANIE AI:", 0, 1)
    
    pdf.set_font(font_main, "", 9)
    pdf.set_text_color(50, 50, 50)
    summary_text = (
        f"Kampania dla klienta {client.name} przebiega stabilnie. "
        f"Uzyskano {stats['replies']} odpowiedzi, w tym {stats['hot_leads']} priorytetowych szans sprzedaży. "
        f"Zalecane jest utrzymanie obecnego tempa wysyłki."
    )
    pdf.multi_cell(180, 5, pdf.safe_text(summary_text))

    # Zapis
    output_path = os.path.join(os.getcwd(), "files", pdf_filename)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf.output(output_path)
    
    print(f"✅ [REPORTER] Wygenerowano raport ENTERPRISE: {output_path}")
    return output_path